"""
Python code executor for scientific simulations.

This version is intentionally less restricted because the app is designed
to run ONLY code generated by the chatbot (not arbitrary user code).

Still not fully unrestricted: no file/network access is intentionally provided,
but normal scientific Python (imports, print, numpy, pandas, etc.) works.
"""

from __future__ import annotations
import io
import traceback
import contextlib
from typing import Dict, Any, Optional
import ast
import sys


def _make_builtins():
    """Return a practical builtins dict for LLM-generated scientific code."""
    import builtins as real_builtins
    b = dict(real_builtins.__dict__)
    return b


def execute_code(
    code: str,
    timeout_seconds: int = 120,
    extra_globals: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Execute Python code and capture stdout, stderr, and a `result` variable.
    """
    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()

    exec_globals: Dict[str, Any] = {
        "__builtins__": _make_builtins(),
        "__name__": "__simulation__",
        "__doc__": None,
    }

    try:
        import numpy as np
        import pandas as pd
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import seaborn as sns
        from scipy import stats, integrate, optimize, signal, ndimage
        import sympy as sp
        import networkx as nx
        from sklearn import datasets, metrics, model_selection, preprocessing
        import statsmodels.api as sm
        import time
        import math
        import random
        from collections import defaultdict, Counter
        from itertools import product, combinations

        exec_globals.update({
            "np": np,
            "numpy": np,
            "pd": pd,
            "pandas": pd,
            "plt": plt,
            "matplotlib": matplotlib,
            "sns": sns,
            "seaborn": sns,
            "stats": stats,
            "integrate": integrate,
            "optimize": optimize,
            "signal": signal,
            "ndimage": ndimage,
            "sp": sp,
            "sympy": sp,
            "nx": nx,
            "networkx": nx,
            "sm": sm,
            "statsmodels": sm,
            "time": time,
            "math": math,
            "random": random,
            "defaultdict": defaultdict,
            "Counter": Counter,
            "product": product,
            "combinations": combinations,
        })
    except ImportError:
        pass

    for mod_name, alias in [
        ("Bio", "Bio"),
        ("numba", "numba"),
        ("lmfit", "lmfit"),
        ("pint", "pint"),
        ("emcee", "emcee"),
        ("astropy", "astropy"),
    ]:
        try:
            mod = __import__(mod_name)
            exec_globals[alias] = mod
        except ImportError:
            pass

    if extra_globals:
        exec_globals.update(extra_globals)

    result_data: Dict[str, Any] = {
        "success": False,
        "stdout": "",
        "stderr": "",
        "error": None,
        "result": None,
    }

    try:
        ast.parse(code)

        with contextlib.redirect_stdout(stdout_capture), contextlib.redirect_stderr(stderr_capture):
            exec(code, exec_globals)

            if "result" in exec_globals:
                result_data["result"] = exec_globals["result"]

        result_data["success"] = True
        result_data["stdout"] = stdout_capture.getvalue()
        result_data["stderr"] = stderr_capture.getvalue()

    except Exception as e:
        result_data["success"] = False
        result_data["stdout"] = stdout_capture.getvalue()
        result_data["stderr"] = stderr_capture.getvalue()
        result_data["error"] = f"{type(e).__name__}: {str(e)}\n{traceback.format_exc()}"

    return result_data


def _format_value(value: Any, max_chars: int = 8000) -> str:
    """Make common scientific objects readable."""
    try:
        import pandas as pd
        if isinstance(value, pd.DataFrame):
            parts = [
                f"DataFrame shape: {value.shape}",
                "",
                "=== head() ===",
                value.head(15).to_string(),
                "",
                "=== describe() ===",
                value.describe(include="all").to_string(),
            ]
            text = "\n".join(parts)
            if len(text) > max_chars:
                return text[:max_chars] + "\n... (truncated)"
            return text
        if isinstance(value, pd.Series):
            text = value.to_string()
            if len(text) > max_chars:
                return text[:max_chars] + "\n... (truncated)"
            return text
    except Exception:
        pass

    try:
        import numpy as np
        if isinstance(value, np.ndarray):
            text = f"ndarray shape={value.shape}, dtype={value.dtype}\n{np.array2string(value, threshold=200)}"
            if len(text) > max_chars:
                return text[:max_chars] + "\n... (truncated)"
            return text
    except Exception:
        pass

    text = str(value)
    if len(text) > max_chars:
        return text[:max_chars] + "\n... (truncated)"
    return text


def format_execution_result(exec_result: Dict[str, Any]) -> str:
    """Turn the execution result into a clean, readable string for the UI and LLM."""
    parts = []

    status = "SUCCESS" if exec_result.get("success") else "FAILED"
    parts.append(f"Execution status: {status}")

    if exec_result.get("stdout"):
        parts.append("=== PRINT OUTPUT ===\n" + exec_result["stdout"].strip())

    if exec_result.get("stderr"):
        parts.append("=== STDERR ===\n" + exec_result["stderr"].strip())

    if exec_result.get("error"):
        parts.append("=== ERROR ===\n" + exec_result["error"].strip())

    if exec_result.get("result") is not None:
        parts.append("=== RESULT VARIABLE ===\n" + _format_value(exec_result["result"]))

    if len(parts) == 1:
        parts.append("(No output produced. Make sure the code prints results or assigns them to a variable named `result`.)")

    return "\n\n".join(parts)
